spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: wo0013
  sql:
    init:
      mode: always
  application:
    name: board

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.group.board.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true